---
title: "gimap for treatment groups"
output: html_document
---
  

```{r}
library(remotes)
remotes::install_github("FredHutch/gimap")
```

```{r}
library(gimap)
library(dplyr)
```

```{r}
output_dir <- "output_data"
dir.create(output_dir, showWarnings = FALSE)
```

## Data loading and setup

```{r}
example_data <- get_example_data("count_treatment")

example_counts <- example_data %>%
  select(c("pretreatment", "dmsoA", "dmsoB", "drug1A", "drug1B")) %>%
  as.matrix()

example_pg_id <- example_data %>%
  dplyr::select("id")

example_sample_metadata <- data.frame(
  col_names = c("pretreatment", "dmsoA", "dmsoB", "drug1A", "drug1B"),
  drug_treatment = as.factor(c("pretreatment", "dsmo", "dsmo", "drug", "drug"))
)


gimap_dataset <- setup_data(counts = example_counts,
                                pg_ids = example_pg_id,
                                sample_metadata = example_sample_metadata
)

nrow(gimap_dataset$transformed_data$log2_cpm)
```  

## QC

```{r}
run_qc(gimap_dataset,
       output_file = "example_qc_report.Rmd",
       overwrite = TRUE,
       quiet = TRUE,
       # TODO: Think about how to specify this for multiple replicates
       # Probably could supply a factor like this that would allow for the same 
       # label to be treated as replicates
       filter_replicates_target_col = factor("A", "B", "B", "C", "C"))
```

## Filtering

```{r}
gimap_dataset <- gimap_dataset %>%
  gimap_filter()
nrow(gimap_dataset$filtered_data$transformed_log2_cpm)
```

## Normalization and calculating scores

```{r}
gimap_dataset <- gimap_dataset %>%
  gimap_annotate(cell_line = "PC9") %>%
  # Whatever is specified for "control_name" is what will be used to normalize other data points
  gimap_normalize(
    treatments = "drug_treatment",
    control_name = "pretreatment") %>%
  calc_crispr() %>%
  calc_gi()
```
